[browser]
gatherUsageStats = false

[server]
runOnSave = true
maxUploadSize = 50
maxMessageSize = 50

[theme]
primaryColor = "#6B46C1"  # More purplish shade
backgroundColor = "#F0F4F8"
secondaryBackgroundColor = "#E9D8FD"  # Light purple
textColor = "#1A202C"